# Site settings
title: Super-Mi
SEOTitle: Super-Mi的博客 | Super-Mi Blog
header-img: img/home-bg.jpg
email: 617991647@qq.com
description: "May Your Heart Be The Map"
keyword: ""
url: "https://Super-Mi.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     huxpro
# zhihu_username:     huxpro
# github_username:    Super-Mi
# twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Support for LiveRe comments system.
# You can get your uid from https://livere.com/insight/myCode (General web site)
# liver settings
livere_uid: MTAyMC80MDQ5NC8xNzAyMQ==

# Disqus settings
# disqus_username: hux

# Netease settings
# netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: 11909588dd7161cadd33fa85ed2b6b76

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: Super-Mi.github.io           


 
# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "美好的事情正在发生！"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "墨灵音乐",
        href: "https://music.mli.im/vip.music"
    },{
        title: "不死鸟",
        href: "https://lai.yuweining.cn/" 
    },{
        title: "在线之家",
        href: "http://www.1993s.top/"
    },{
        title: "w3school",
        href: "http://www.w3school.com.cn/"
    },{
        title: "脚本之家",
        href: "https://m.jb51.net/"
    },{
        title: "Huxpro",
        href: "https://github.com/Huxpro/huxpro.github.io"
    },{
        title: "Yosoro/markdown",
        href: "https://github.com/IceEnd/Yosoro/blob/master/CHANGELOG.md"
    },{
        title: "富天博客",
        href: "http://www.mafutian.net/"
    },{
        title: "Hux Blog",
        href: "http://huangxuan.me/"
    },{
        title: "Dr-F",
        href: "https://dreaming-forest.github.io/"
    },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    },{
        title: "解旻的博客",
        href: "http://xieminis.me/"
    }
]
